### ISSUE TITLE
Use developit/proptypes for the entire set of PropTypes?

### ISSUE THREAD

**Issue by sompylasar** [aackerman/PropTypes#3]
The https://github.com/developit/proptypes module provides the entire set of `PropTypes`, so instead of defining a subset, why not use the entire set to make it a truly drop-in replacement?

**Comment by sompylasar** [comment]
This becomes of a high importancy for teams who use PropTypes validation in production because of https://fb.me/react-warning-dont-call-proptypes -- the article even links to these two repos.

**Comment by zhuangya** [comment]
@sompylasar maybe we should notice fb team to update the link :/

**Comment by aackerman** [comment]
I'm going to go ahead and close this, the react team has taken over the releases of `prop-types` on npm.
