### ISSUE TITLE
how to check which PropType given the checker function?

### ISSUE THREAD

**Issue by plantvsbirds** [aackerman/PropTypes#4]
I have a react component imported and its `.propTypes` available, i.e. a map of all prop names to their checker function. Now I would like to get their types.

All I can think of is to feed each checker function with some value and find out. It should work totally fine for native value. But is there a more proper way to do this?

**Comment by aackerman** [comment]
Hi @plantvsbirds if you are using version 0.2.0 or earlier of prop-types I can try to answer. Any versions 15+ belong to the react team and I would direct you to post your question to stackoverflow and get some help from the community.

**Comment by plantvsbirds** [comment]
I will post this to appropriate place. Thank you!
Aaron Ackerman <notifications@github.com>于2017年6月13日 周二20:09写道：
